### ISSUE TITLE
After upgrade to latest version(2) from 1.0.0 failed to add doc

### ISSUE THREAD

**Issue by Tim-Jin** [olivernn/lunr.js#258]
```
this.index = lunr(function(){
        this.field('title', { boost: 10 });
        this.field('content');
 `});
```

`this.index.add(doc);  //failed with "this.index.add is not a function"`

**Comment by et1421** [comment]
Seems like this feature is no longer available : https://lunrjs.com/guides/upgrading.html

**Comment by Tim-Jin** [comment]
got it. Thank you very much.
